#!/bin/dash
# A dmenu wrapper script for system functions.
case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

case $BLOCK_BUTTON in
  1) case "$(echo "🔒 lock\n🚪 leave dwm\n🟦 renew dwm\n🐻 hibernate\n🟢 reboot\n🔴 shutdown\n💤 sleep\n📺 display off" | dmenu -fn monospace:pixelsize=14 -nb \#282828 -nf \#bbbbbb -sb \#d71513 -sf \#eeeeee -l 8 -i -p 'what do?')" in
    '🔒 lock') slock ;;
    '🚪 leave dwm') kill -TERM "$(pgrep -u "$USER" "\bdwm$")" ;;
    '🟦 renew dwm') kill -HUP "$(pgrep -u "$USER" "\bdwm$")" ;;
    '🐻 hibernate') slock $ctl hibernate ;;
    '💤 sleep') slock $ctl suspend ;;
    '🟢 reboot') $ctl reboot -i ;;
    '🔴 shutdown') $ctl poweroff -i ;;
    '📺 display off') xset dpms force off ;;
    esac
  ;;
	6) st -e "$EDITOR" "$0" ;;
esac

echo "🔴"
